BaseURL = "https://annaamalaiorthospine.com/"
languageCode = "en-us"
title = "Annaamalai Ortho and Spine Center"
theme = "samhugobs5theme"
relativeURLS = true

  [permalinks]
    services = ":title/"
    blogs = ":title/"
    case-studies = ":title/"

  [params]
    author = "Dr Vignesh Pushparaj"
    linkedinurl  = ""
    facebookurl  = "https://www.facebook.com/annaamalaiorthospine/"
    telephone = "+914448545655"
    email     = "info@annaamalaiorthospine.com"
    twitterurl   = ""
    whatsappnumber = "919150955655"
    instagramurl = "https://www.instagram.com/annaamalaiortho/"
    icon = "/assets/images/annaamalai-wings.png"
    logo = "/assets/images/annaamalai-ortho-and-spine-center-logo.png"
    logowebp = "/assets/images/annaamalai-ortho-and-spine-center-logo.webp"
    logoalt  = "Annaamalai Ortho and Spine Center Logo"
    bannerimage = "annaamalai-osc"
    banneralt = "A woman in a Yoga posture"  
    title = "Annaamalai Ortho and Spine Center"
    description = "Annaamalai Ortho and Spine Centre is a state of the art ortho spine treatment unit in thiruvanmaiyur, chennai. It is a one of a kind, ultramodern clinic with all orthopaedic treatment facilities under one roof.such as xray, physiotherapy, pharma dispencery and specialist consultation. Here, we treat patients suffering from low back, neck pain, congenital bone problems,joint arthritis, fractures including spine and long bones , degenerative spine problems and other tendon related injuries with scientifically proven, updated and well accepted treatment at an affordable cost. We have a fully equipped and functioning stemcell harvesting centre, minor procedure space. We are headed by internationaly trained Dr. Vignesh pushparaj. We aim to provide the best of care at an affordable price to our patients."
    images = ["/assets/images/live-pain-free-1200x550.jpg", "/assets/images/annaamalai-ortho-and-spine-center-logo.png"]
  
  [module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"

  [frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":fileModTime", ":default"]

  sectionPagesMenu = "main"

  [menu]

    [[menu.main]]
      identifier = "services"
      title = "Services"
      url = "#services"
      weight = 200
    
    [[menu.main]]
      identifier = "blog"
      title = "Blog"
      url = "#blogs"
      weight = 300